name: Wake Aiven MySQL

on:
  workflow_dispatch:

  schedule:
    - cron: "0 */6 * * *"

jobs:
  wake-db:
    runs-on: ubuntu-latest

    steps:
      - name: Install Aiven CLI
        run: pip install aiven-client

      - name: Power on MySQL
        env:
          AIVEN_AUTH_TOKEN: ${{ secrets.AIVEN_TOKEN }}
        run: |
          avn service update mysql-3b347bbd \
            --project rojadevi08-86a4 \
            --power-on

      - name: Wait for MySQL
        env:
          AIVEN_AUTH_TOKEN: ${{ secrets.AIVEN_TOKEN }}
        run: |
          avn service wait mysql-3b347bbd \
            --project rojadevi08-86a4