name: Wake Aiven MySQL

on:
  workflow_dispatch:

jobs:
  wake-db:
    runs-on: ubuntu-latest

    steps:
      - name: Install Aiven CLI
        run: pip install aiven-client

      - name: Configure Aiven CLI
        env:
          AIVEN_TOKEN: ${{ secrets.AIVEN_TOKEN }}
          AIVEN_EMAIL: ${{ secrets.AIVEN_EMAIL }}
        run: |
          mkdir -p ~/.config/aiven

          cat > ~/.config/aiven/aiven-credentials.json <<EOF
          {
            "auth_token": "$AIVEN_TOKEN",
            "user_email": "$AIVEN_EMAIL"
          }
          EOF

      - name: Power on MySQL
        run: |
          avn service update mysql-3b347bbd --power-on

      - name: Wait for MySQL
        run: |
          avn service wait mysql-3b347bbd